# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jesper Westervig Nielsen
title: iOS Developer
email: jesper@app-it.dk
website: www.github.com/iosGeekster

# Social links
twitter_username: iosgeekster
github_username:  iosgeekster
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: iosgeekster
linkedin_username: jesper84
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! My name is Jesper. I'm a passinate iOS Developer.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Metallica (Closing in on 20 concerts)
   - Cooking
   - Listening to- and collecting vinyls

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
